name: deploy

on:
  repository_dispatch:
    types: [stack-deploy]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  ENVIRONMENT: ${{ github.event.client_payload.environment }}
  STACK: ${{ github.event.client_payload.stack }}
  BRANCH: release/stack-${{ github.event.client_payload.stack }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Pull code
      uses: actions/checkout@v2
      with:
        token: ${{ env.GITHUB_TOKEN }}
        fetch-depth: '0'
        submodules: 'recursive'
    
    - name: Create or update release branch
      run: |
        # Add submodule
        if [ ! -d "stack-${STACK}" ]; then
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule add git@github.com:fedjabosnic/tf-stack-${STACK}.git stack-${STACK}
          git submodule update --remote
          echo " ${STACK}" >> .variables/stacks
        fi

        # Update submodule
        STACK_BASE=$(git submodule status stack-${STACK} | cut -c 2-9)
        cd stack-${STACK} && git fetch --all && git checkout ${ENVIRONMENT} && cd ..
        STACK_HEAD=$(git submodule status stack-${STACK} | cut -c 2-9)

        # Prepare commit message
        STACK_DIFF=$(git diff --submodule=log stack-${STACK} | sed '1G' | sed 's/  </-/g' | sed 's/  >/-/g')

        STACK_DIFF="${STACK_DIFF//'%'/%25}"
        STACK_DIFF="${STACK_DIFF//$'\n'/%0A}"
        STACK_DIFF="${STACK_DIFF//$'\r'/%0D}"

        echo ::set-env name=STACK_BASE::${STACK_BASE}
        echo ::set-env name=STACK_DIFF::${STACK_DIFF}
        echo ::set-env name=STACK_HEAD::${STACK_HEAD}

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        commit-message: "stack-${{ env.STACK }} @ ${{ env.STACK_HEAD }}"
        branch: ${{ env.BRANCH }}
        title: "Release: stack-${{ env.STACK }} @ ${{ env.STACK_HEAD }}"
        body: ${{ env.STACK_DIFF }}
        assignees: |
          bot-digit
        reviewers: |
          fedjabosnic
          oliverdon
        #team-reviewers: /b2c
        