name: deploy

on:
  repository_dispatch:
    types: [stack-deploy]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  ENVIRONMENT: ${{ github.event.client_payload.environment }}
  STACK: ${{ github.event.client_payload.stack }}
  BRANCH: release/auto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Pull code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    
    - name: Create or update release branch
      run: |
        # Create branch
        git checkout -B ${BRANCH}

        # Add submodule
        if [ ! -d "stack-${STACK}" ]; then
          git submodule add git@github.com:fedjabosnic/tf-stack-${STACK}.git stack-${STACK}
          git submodule update --remote
        fi

        # Update submodule
        STACK_BASE=$(git submodule status stack-${STACK} | cut -c 1-8)
        cd stack-${STACK} && git fetch --all && git checkout ${ENVIRONMENT} && cd ..
        STACK_HEAD=$(git submodule status stack-${STACK} | cut -c 1-8)

        # Prepare commit message
        STACK_DIFF=$(git diff --submodule=log stack-${STACK} | sed '1G' | sed 's/  </-/g')

        git add .
        git config --global user.email "fedjabosnic@gmail.com"
        git config --global user.name "fedjabosnic"
        git commit -m "${STACK_DIFF}" || echo "No changes to commit"

    - name: Create or update pull request
      uses: gr2m/create-or-update-pull-request-action@v1.x
      with:
        branch: ${{ env.BRANCH }}
        title: "Release: auto-generated"
        body: "Auto-generated release based on stack changes"
        