name: promote

on:
  repository_dispatch:
    types: [promote-stack]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  SSH_KEY: ${{ secrets.BOT_SSH_KEY }}
  STACK: ${{ github.event.client_payload.stack }}
  ACTOR: ${{ github.event.client_payload.actor }}
  SHA: ${{ github.event.client_payload.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Pull code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ env.SSH_KEY }}

    - name: Prepare stack changes
      run: |
        # Add submodule
        if [ ! -d "stack-${STACK}" ]; then
          git submodule add git@github.com:fedjabosnic/tf-stack-${STACK}.git stack-${STACK}
          echo " ${STACK}" >> .variables/stacks
        fi
        
        # Update submodule
        git submodule init
        git submodule update
        cd stack-${STACK} && git fetch --all && git checkout ${SHA} && cd ..

        # Prepare commit message
        STACK_DIFF=$(git diff --submodule=log stack-${STACK} | sed '1G' | sed 's/  </-/g' | sed 's/  >/-/g')
        STACK_DIFF="${STACK_DIFF//'%'/%25}"
        STACK_DIFF="${STACK_DIFF//$'\n'/%0A}"
        STACK_DIFF="${STACK_DIFF//$'\r'/%0D}"

        echo ::set-env name=STACK_DIFF::${STACK_DIFF}

    - name: Create branch and pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        branch: "release/stack-${{ env.STACK }}"
        commit-message: "stack-${{ env.STACK }} @ ${{ env.SHA }}"
        title: "Release: stack-${{ env.STACK }} @ ${{ env.SHA }}"
        body: ${{ env.STACK_DIFF }}
        assignees: |
          ${{ env.ACTOR }}
        reviewers: |
          fedjabosnic
          oliverdon
        #team-reviewers: /b2c
